# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mvc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DeptCode',
            field=models.ForeignKey(db_column='DeptCode_DeptCode', on_delete=django.db.models.deletion.CASCADE, to='app_mvc.Department'),
        ),
    ]
